// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZAUVeN3FzeN070_KRudUEHiJXTZoiFJ4',
    appId: '1:107620755615:web:f40498552d1634b1581aaa',
    messagingSenderId: '107620755615',
    projectId: 'chat-app-1fd35',
    authDomain: 'chat-app-1fd35.firebaseapp.com',
    storageBucket: 'chat-app-1fd35.appspot.com',
    measurementId: 'G-B8DSDLVMMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAExx_CrBiHCNv5xz6ODgQCvermeArbc5A',
    appId: '1:107620755615:android:a02eb114ae6db998581aaa',
    messagingSenderId: '107620755615',
    projectId: 'chat-app-1fd35',
    storageBucket: 'chat-app-1fd35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGfiBpoENVGWcB5bI3jECkxybw4jhP6G4',
    appId: '1:107620755615:ios:887e3813a7653cf2581aaa',
    messagingSenderId: '107620755615',
    projectId: 'chat-app-1fd35',
    storageBucket: 'chat-app-1fd35.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
